NSDesai/Controllers/InquiryController.cs
using NSDesai.ModelClass;
using NSDesai.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Validation;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace NSDesai.Controllers
{
   [ValidateModelStateAttributes]
    public class InquiryController : Controller
    {
        private nconin_PropertyUATEntities dbset;
       
        public InquiryController()
        {
            dbset = new nconin_PropertyUATEntities();
        }
        // GET: Inquiry
        [HttpGet]
        public ActionResult Index(string mobileno = null)
        {
            FormCollection frm = new FormCollection();
            //string mobileno1 = Request.Form["mobileno"];                      
            //dynamic mutiplemodel = new ExpandoObject();
            //mutiplemodel.calldetails = new tblcall();
            //mutiplemodel.callerdetails = new tblcaller();   
            tblcall calldetails = new tblcall();
            tblcaller callerdetails = new tblcaller();
            if (mobileno != null)
            {
                ViewBag.MobielNoEx = mobileno;
                callerdetails.idcaller = dbset.tblcallers.Where(x => x.Mobile == mobileno).Select(x => x.idcaller).FirstOrDefault();
            }
            var TupleModel = new Tuple<tblcall,tblcaller>(calldetails,callerdetails);
            List<string> propertylist = ConfigurationManager.AppSettings["PropertyName"].ToString().Split(',').Select(x => x.Trim()).ToList();
            ViewBag.propertylist = propertylist;
            List<string> callertypelist = ConfigurationManager.AppSettings["Callertype"].ToString().Split(',').Select(x => x.Trim()).ToList();
            ViewBag.callertypelist = callertypelist;
            List<string> propertype = ConfigurationManager.AppSettings["Propertytype"].ToString().Split(',').Select(x => x.Trim()).ToList();
            ViewBag.propertypelist = propertype;            
            return View(TupleModel);
        }

        [HttpPost]
      //  [ValidateModelStateAttributes]
      //  [ValidateModelStateAttributes]
        public ActionResult Index(tblcall item1,tblcaller item2)
        {
            item1.idstaff = 0;
            if (ModelState.IsValid)
            {
                try
                {

                    if (item2.idcaller > 0)
                    {
                        item1.idcaller = item2.idcaller;
                        dbset.tblcalls.Add(item1);
                    }
                    else
                    {
                        dbset.tblcallers.Add(item2);
                        dbset.SaveChanges();
                        item1.idcaller = item2.idcaller;
                        dbset.tblcalls.Add(item1);
                    }


                    dbset.SaveChanges();
                }
                catch (DbEntityValidationException ex)
                {
                    Exception raise = ex;
                    foreach (var validationErrors in ex.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            string message = string.Format("{0}:{1}",
                                validationErrors.Entry.Entity.ToString(),
                                validationError.ErrorMessage);
                            // raise a new exception nesting  
                            // the current instance as InnerException  
                            raise = new InvalidOperationException(message, raise);
                        }
                    }

                    throw raise;
                }

                return RedirectToAction("GetGridList");
            }
            else
            {
                item2.idcaller = 0;
                List<string> propertylist = ConfigurationManager.AppSettings["PropertyName"].ToString().Split(',').Select(x => x.Trim()).ToList();
                ViewBag.propertylist = propertylist;
                List<string> callertypelist = ConfigurationManager.AppSettings["Callertype"].ToString().Split(',').Select(x => x.Trim()).ToList();
                ViewBag.callertypelist = callertypelist;
                List<string> propertype = ConfigurationManager.AppSettings["Propertytype"].ToString().Split(',').Select(x => x.Trim()).ToList();
                ViewBag.propertypelist = propertype;
                var TupleModel = new Tuple<tblcall, tblcaller>(new tblcall(), new tblcaller());
                return View(TupleModel);
            }
        }
        
        [HttpGet]
        public JsonResult GetCallerInquirtyByMobile(string Mobile)
        {
            var CallerData = dbset.tblcallers.Where(x => x.Mobile == Mobile).FirstOrDefault();
            var InquiryData = dbset.tblcalls.Where(x => x.idcaller == CallerData.idcaller).ToArray();
            CallerWithInquiryModel CImodel = new CallerWithInquiryModel();
            CImodel.callerDetails = CallerData;
            CImodel.inquiryDetails = InquiryData;
            return Json(CImodel, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetGridList()
        {
            return View();
        }
        [HttpGet]
        public JsonResult GetAllCallerDetails()
        {
            var inquirywithcaller = (from i in dbset.tblcalls
                                     join j in dbset.tblcallers on i.idcaller equals j.idcaller
                                     select new { txtrequirementtype = i.txtrequirementtype, txtinquiryproject = i.txtinquiryproject, txtpurpose = i.txtpurpose, FirstName = j.FirstName, Mobile = j.Mobile, City = j.City, Email = j.Email,callerid = j.idcaller }).ToList();
                                   
            return Json(inquirywithcaller,JsonRequestBehavior.AllowGet);
        }        
    }
}

NSDesai/Views/Inquiry/GetGridList.cshtml
@{
    ViewBag.Title = "GetGridList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center"> Inquiry List</h2>
<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card bootstrap-table">
                    <div class="card-body table-full-width">
                        <div class="toolbar">
                        </div>
                        <table id="bootstrap-table" class="table">
                            <thead>
                            <th style="display:none">Id</th>
                            <th data-sortable="true">Name</th>
                            <th data-sortable="true">Mobile</th>
                            <th data-sortable="true">Type</th>
                            <th data-sortable="true">Project</th>
                            <th data-sortable="true">Purpose</th>
                            <th data-sortable="true">Email</th>
                            <th data-sortable="true">City</th>
                            <th class="td-actions text-right" data-events="operateEvents" data-formatter="operateFormatter">Actions</th>
                            </thead>
                            <tbody id="tabledata"></tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
<script>
        var table = $('#bootstrap-table');
        function operateFormatter(value, row, index) {
            return [
                '<a rel="tooltip" title="View" class="btn btn-link btn-info table-action view" href="javascript:void(0)">',
                '<i class="fa fa-image"></i>',
                '</a>',
                '<a rel="tooltip" title="Edit" class="btn btn-link btn-warning table-action edit" href="javascript:void(0)">',
                '<i class="fa fa-edit"></i>',
                '</a>',
                '<a rel="tooltip" title="Remove" class="btn btn-link btn-danger table-action remove" href="javascript:void(0)">',
                '<i class="fa fa-remove"></i>',
                '</a>',
                '<button rel="tooltip" title="Add Inquiry" class="btn btn-link btn-info table-action remove" onclick="getcurrentdata(this)">',
                '<i class="fa fa-file"></i>',
                '</button>'
            ].join('');
        }
        $().ready(function () {

            $('#bootstrap-table').bootstrapTable({

                'url': "/Inquiry/GetAllCallerDetails/",
                'type': "GET",
                //"processing": true,
               // "serverSide": true,
                //"ajax": "/Inquiry/GetAllCallerDetails/",
                //"type" : "GET",
                "columns": [
                    {
                        "data": "callerid",
                        field: "callerid",
                        visible:false
                    },
                    {
                        "data": "FirstName",
                        field: "FirstName"
                    },
                    {
                        "data": "Mobile",
                        field: "Mobile"
                    },
                    {
                        "data": "txtrequirementtype",
                        field: "txtrequirementtype"
                    },
                    {
                        "data": "txtpurpose",
                        field: "txtpurpose"
                    },
                    {
                        "data": "txtinquiryproject",
                        field: "txtinquiryproject"
                    },
                    {
                        "data": "Email",
                        field: "Email"
                    },
                    {
                        "data": "City",
                        field: "City"
                    }

                ],
                toolbar: ".toolbar",

    clickToSelect: true,
    showRefresh: true,
    search: true,
    showToggle: true,
    showColumns: true,
    pagination: true,
    searchAlign: 'left',
    pageSize: 8,
    clickToSelect: false,
    pageList: [8, 10, 25, 50, 100],

    formatShowingRows: function(pageFrom, pageTo, totalRows) {
    //do nothing here, we don't want to show the text "showing x of y from..."
    },
    formatRecordsPerPage: function(pageNumber) {
    return pageNumber + " rows visible";
    },
                formatNoMatches: function () {

                    return 'No matching records found';
                },
    icons: {
    refresh: 'fa fa-refresh',
    toggle: 'fa fa-th-list',
    columns: 'fa fa-columns',
    detailOpen: 'fa fa-plus-circle',
    detailClose: 'fa fa-minus-circle'
    }
            });
          //  column(0).visible(false);


    //activate the tooltips after the data table is initialized
            $('[rel="tooltip"]').tooltip();

    $(window).resize(function() {
        $('#bootstrap-table').bootstrapTable('resetView');
            });

            var inqirydata = "<button class='btn btn-outline' type='button name='Add Inquiry' id='btnaddinquiry' title='Add User Inquiry' onclick='addnewinqiry()'><i class='glyphicon fa fa-user-plus'></i></button>";
            $(".columns-right").append(inqirydata);

        });

        function getcurrentdata(item) {
            
            var data = $(item).closest("tr")   // Finds the closest row <tr>
                .find("td:eq(1)")     // Gets a descendent with class="nr"
                .text();
           var link = '@Url.Action("Index", "Inquiry", new { mobileno = "replace" })';
            link = link.replace("replace", data);
            window.location = link;

        }


    function addnewinqiry() {
        window.location.href =  '@Url.Action("Index","Inquiry")';
        }

</script>

}